import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import style from "./layout.module.css";
import Image from "next/image";
// import IconSearchBar from "/public/icons/search-bar.png";
import IconSearchBar2 from "/public/icons/icons8-search.svg";
import { IBM_Plex_Sans_KR } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notosansMono = IBM_Plex_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavigationBar() {
  return (
    <div className={style.navigationBar}>
      <nav>
        <Link href="/" className={style.navItem}>
          홈
        </Link>
        <Link href="/explore" className={style.navItem}>
          탐색
        </Link>
        <Link href="/my" className={style.navItem}>
          마이페이지
        </Link>
      </nav>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notosansMono.className}`}>
        <div className={style.container}>
          <div className={style.innerContainer}>
            <header>
              <Link href={"/"}>⛰️ 봉우리</Link>
              {/* <Link href={"/search"}>
                <Image
                  src={IconSearchBar2}
                  alt="search-bar"
                  width={32}
                  height={32}
                />
              </Link> */}
            </header>
            <main>{children}</main>
            <NavigationBar />
          </div>
        </div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
